Hourlyapi
IsaacM890/weather-app pull request #1
Opened 2020-12-31 14:13 UTC by IsaacM890

2021-01-04 10:23 UTC, almogbhl requested changes

2021-01-04 10:23 UTC, almogbhl commented on src/api/index.js
> +export const getAutoCompleteList = (input) =>
change 'input' for a better name

2021-01-04 10:23 UTC, almogbhl commented on src/api/index.js
> +export const getCurrentConditions = (Key) =>
change 'key' for a better name

2021-01-04 10:23 UTC, almogbhl commented on src/api/index.js
> +    `ushttp://dataservice.accuweather.com/locations/v1/cities/autocomplete?apikey=${process.env.REACT_APP_API_KEY}&q=${input}`
Whenever you see you repeat yourself - like in the base URL - maybe keep it as a variable?

2021-01-04 10:23 UTC, almogbhl commented on src/api/index.js
> +import Axios from 'axios';
change to axios, why Axios

2021-01-04 10:23 UTC, almogbhl commented on package.json
> +    "dotenv": "^8.2.0",
great implementation  of env

2021-01-04 10:23 UTC, almogbhl commented on src/components/CurrentForcast/CurrentForcast.jsx
> +        <SCloudicon
SCloudIcon

2021-01-04 10:23 UTC, almogbhl commented on src/components/CurrentForcast/CurrentForcast.jsx
> +  const timePattern = { hour: 'numeric', minute: 'numeric' };
pls use destructuring for props

2021-01-04 10:23 UTC, almogbhl commented on src/components/ForecastList/ForecastList.jsx
> +    margin-left: 0px;
no need for px, just 0

2021-01-04 10:23 UTC, almogbhl commented on src/components/ForecastList/ForecastList.jsx
>              <Card
extract card as a component

2021-01-04 10:23 UTC, almogbhl commented on src/components/ForecastList/ForecastList.jsx
> +                  src={`http://vortex.accuweather.com/adc2010/images/slate/icons/${item.WeatherIcon}.svg`}
add utils function of getWeatherIcon = icon => `http://vortex.accuweather.com/adc2010/images/slate/icons/${item.WeatherIcon}.svg`

so it will be:
<SCardIcon  src={getWeatherIcon(item.WeatherIcon)} ... />

2021-01-04 10:23 UTC, almogbhl commented on src/components/Headline/Headline.jsx
> +  font-size: ${(props) => props.fontsize};
when u have a lot of props, maybe a cleaner way - refactor all of those to be:
```
const SHeadline = styled.div(({color, text})=> (
`
   color: ${color};
   text: ${text};
`))
```

2021-01-04 10:23 UTC, almogbhl commented on src/components/Headline/Headline.jsx
>        margin={margin}
I don't like passing props as margin or font size, should be hard coded

2021-01-04 10:23 UTC, almogbhl commented on src/components/Searchinput/Searchinput.jsx
> +  &:focus-within ul {
if this is for the ul, why not be more clear and add it to the const SDropdownList = styled.ul`?

2021-01-04 10:23 UTC, almogbhl commented on src/components/Searchinput/Searchinput.jsx
> +    background-color: #F2C2BE;
I want you to be more clear for others when they read your code, by using vars for unclear properties 

create a theme.js file which will be an object you will pass to the style-component themeProvider

example of the theme obj:
```
const theme = {
 colors: {
    primary: '#F2C2BE',
    secondary: '#...'
 },
 breakpoints: {
   mobile: '...',
   tablet: '768px',
    desktop: '...'
 }
}
```
how to use example:

```
const SHeadline = styled.div((theme)=> (
`
   background-color: ${theme.colors.primary};
   @media (max-width: ${theme.breakpoints.tablet}) {
      width: 70%;	  
    }	  
}
`))
```

more clear and clean

2021-01-04 10:23 UTC, almogbhl commented on src/components/Searchinput/Searchinput.jsx
> +          <SDropDownItem onMouseDown={() => props.onSelectOption(item)} key={index}>
key={index} really bad practice - read about it and explain to me why and what is the solution

2021-01-04 10:23 UTC, almogbhl commented on src/components/Searchinput/Searchinput.jsx
> +        placeholder={'Type Here ... '}
'Search'

2021-01-04 10:23 UTC, almogbhl commented on src/components/Searchinput/Searchinput.jsx
> +      <SSearchinput
SSearchInput

2021-01-04 10:23 UTC, almogbhl commented on src/helpers/index.js
> +export const getDate = (item, type) => {
write a few comments to understand it better

2021-01-04 10:23 UTC, almogbhl commented on src/pages/WeatherPage.js
> +    console.log(response.data);
rm unused code like logs

2021-01-04 10:23 UTC, almogbhl commented on src/pages/WeatherPage.js
> +    await getForcast(option.Key);
talk to me about it

2021-01-05 16:30 UTC, IsaacM890 commented on src/api/index.js
> +export const getAutoCompleteList = (input) =>
changed to query

2021-01-05 18:22 UTC, IsaacM890 commented on src/api/index.js
> +export const getCurrentConditions = (Key) =>
changed to cityKey

2021-01-05 18:22 UTC, IsaacM890 commented on src/api/index.js
> +    `ushttp://dataservice.accuweather.com/locations/v1/cities/autocomplete?apikey=${process.env.REACT_APP_API_KEY}&q=${input}`
handeled

2021-01-05 18:22 UTC, IsaacM890 commented on src/api/index.js
> +import Axios from 'axios';
checked

2021-01-05 18:37 UTC, IsaacM890 commented on src/components/CurrentForcast/CurrentForcast.jsx
> +  const timePattern = { hour: 'numeric', minute: 'numeric' };
handeled

2021-01-05 18:38 UTC, IsaacM890 commented on src/components/CurrentForcast/CurrentForcast.jsx
> +        <SCloudicon
checked

2021-01-05 18:39 UTC, IsaacM890 commented on src/components/ForecastList/ForecastList.jsx
> +                  src={`http://vortex.accuweather.com/adc2010/images/slate/icons/${item.WeatherIcon}.svg`}
checked

2021-05-06 17:35 UTC, merged